# Generated by Django 4.2.7 on 2024-01-28 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_workspace_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='files',
            field=models.ManyToManyField(related_name='files', to='base.files'),
        ),
        migrations.AlterField(
            model_name='files',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='base.workspace'),
        ),
    ]
