# Generated by Django 4.2.7 on 2024-02-01 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_workspace_files_alter_files_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='location',
            field=models.FileField(null=True, upload_to='workspace_files/'),
        ),
        migrations.AlterField(
            model_name='files',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='base.workspace'),
        ),
    ]
