# Generated by Django 4.2.7 on 2024-02-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_notes_remove_workspace_files_delete_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='links',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
